### ISSUE TITLE
Match vision stats breaks SPA

### ISSUE THREAD

**Issue by JaffarA** [odota/web#2908]
**Current Behavior**
Going to any parsed match and clicking the vision tab will cause the page to go blank. since the page is a SPA it breaks site functionality until page is refreshed.

```https://www.opendota.com/matches/6420560765``` - works
```https://www.opendota.com/matches/6420560765/vision``` - breaks site

All other tabs work so I'm assuming this broke in the latest release.

**Expected behavior/code**
Vision tag loads and shows vision stats for that match.

**Console Output**
```
27d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1 TypeError: Cannot read properties of undefined (reading 'value')
    at k (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2023688)
    at sortFn (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2024347)
    at 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2475725
    at Array.map (<anonymous>)
    at 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2475494
    at Array.map (<anonymous>)
    at t.value (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2475404)
    at Qi (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1396609)
    at Ji (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1396402)
    at As (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1431870)
gs @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Cs.n.callback @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
To @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
xo @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Il @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Dl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
kl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Jr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Zr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
gl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
enqueueSetState @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
v.setState @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
requestAnimationFrame (async)
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
requestAnimationFrame (async)
value @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Il @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Dl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
kl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Jr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Zr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
se @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
En @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1 TypeError: Cannot read properties of undefined (reading 'value')
    at 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2078480
    at Array.map (<anonymous>)
    at er (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2079183)
    at hi (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1385190)
    at As (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1430602)
    at Pl (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1416124)
    at Ml (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1416049)
    at kl (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1413369)
    at 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1371474
    at t.unstable_runWithPriority (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1446547)
gs @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Cs.n.callback @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
To @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
xo @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Il @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Dl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
kl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Jr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Zr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
gl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
enqueueSetState @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
v.setState @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
requestAnimationFrame (async)
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
requestAnimationFrame (async)
value @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Il @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Dl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
kl @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
(anonymous) @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
t.unstable_runWithPriority @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Vr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Jr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
Zr @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
se @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
En @ 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1
7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at k (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2023688)
    at sortFn (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2024347)
    at 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2475725
    at Array.map (<anonymous>)
    at 7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2475494
    at Array.map (<anonymous>)
    at t.value (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:2475404)
    at Qi (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1396609)
    at Ji (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1396402)
    at As (7d6d9d22236faef8fbb1cbcbb3377e38081569a7.js:1:1431870)
```

**Environment**
- Browser Version: Brave ```([Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)])``` & Firefox Developer Edition ```98.0b8 (64-bit)```
- OS: Windows 10 Pro ```Version 10.0.19042 Build 19042``` and Manjaro Linux ```Kernel: 5.14.21-2-MANJARO```

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/5521781/155574380-bdeea30a-c46f-4fc4-8e00-cfaf93d1dcc4.png)

![image](https://user-images.githubusercontent.com/5521781/155574334-5bfc531d-9cee-4afd-bdc3-136c33533aab.png)

**Comment by howardchung** [comment]
I assume this was due to an item change in the patch
